AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0
Description: 'AWS CloudFormation Sample Template EC2InstanceWithSecurityGroupSample:
  Create an Amazon EC2 instance running the Amazon Linux AMI. The AMI is chosen based
  on the region in which the stack is run. This example creates an EC2 security group
  for the instance to give you SSH access. **WARNING** This template creates an Amazon
  EC2 instance. You will be billed for the AWS resources used if you create a stack
  from this template.'
Parameters:
  Env:
    Type: String
  VPCName:
    Type: String
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t3.small
    AllowedValues: [t2.nano, t2.micro, t2.small, t2.medium, t2.large, t2.xlarge, t2.2xlarge,
      t3.nano, t3.micro, t3.small, t3.medium, t3.large, t3.xlarge, t3.2xlarge]
    ConstraintDescription: must be a valid EC2 instance type.
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  LatestAmiId:
    Type:  'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

Resources:
  publicEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref 'InstanceType'
      KeyName: !Ref 'KeyName'
      ImageId: !Ref 'LatestAmiId'
      NetworkInterfaces: 
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          DeleteOnTermination: true
          GroupSet: 
            - Ref: "InstanceSecurityGroup"
          SubnetId:
            Fn::ImportValue: !Sub "${Env}-public-subnet-id"
      Tags:
        - Key: Name
          Value: !Sub "${Env}-public-instance"
        - Key: Course
          Value: DevOps
  
  privateEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref 'InstanceType'
      KeyName: !Ref 'KeyName'
      ImageId: !Ref 'LatestAmiId'
      NetworkInterfaces: 
        - AssociatePublicIpAddress: false
          DeviceIndex: "0"
          DeleteOnTermination: true
          GroupSet: 
            - Ref: "InstanceSecurityGroup"
          SubnetId:
            Fn::ImportValue: !Sub "${Env}-private-subnet-id"
      Tags:
        - Key: Name
          Value: !Sub "${Env}-private-instance"
        - Key: Course
          Value: DevOps
  dataEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref 'InstanceType'
      KeyName: !Ref 'KeyName'
      ImageId: !Ref 'LatestAmiId'
      NetworkInterfaces: 
        - AssociatePublicIpAddress: false
          DeviceIndex: "0"
          DeleteOnTermination: true
          GroupSet: 
            - Ref: "InstanceSecurityGroup"
          SubnetId:
            Fn::ImportValue: !Sub "${Env}-data-subnet-id"
      Tags:
        - Key: Name
          Value: !Sub "${Env}-data-instance"
        - Key: Course
          Value: DevOps

  # Security Group
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: !Ref 'SSHLocation'
      VpcId:
        Fn::ImportValue: !Sub "${Env}-${VPCName}-id"

Outputs:
  PublicInstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref 'publicEC2Instance'
  PublicInstanceDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt [publicEC2Instance, PublicDnsName]
  PublicInstanceIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt [publicEC2Instance, PublicIp]

  PrivateInstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref 'privateEC2Instance'
  PrivateInstanceDNS:
    Description: Private DNSName of the newly created EC2 instance
    Value: !GetAtt [privateEC2Instance, PrivateDnsName]
  PrivateInstanceIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt [privateEC2Instance, PrivateIp]

  DataInstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref 'dataEC2Instance'
  DataInstanceDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt [dataEC2Instance, PrivateDnsName]
  DataInstanceIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt [dataEC2Instance, PrivateIp]
